Edit vue-router routes to comply with description in Jira
TechLadies/irrc-madwish pull request #30
Opened 2020-11-07 06:32 UTC by dzldebby

- /new-student
- /edit-student/:id
- /students (all students)

2020-11-07 08:01 UTC, thchia requested changes
Suggest you separate the changes regarding the Students table and the routes.

2020-11-07 08:01 UTC, thchia commented on frontend/src/pages/Students.vue
> +
This file should not be in this PR, it's part of the Table PR. Remember to start a new branch from master when making new PRs.

2020-11-07 08:01 UTC, thchia commented on frontend/src/router.js
> +    { path: "/students", component: Students },
Technically, you cannot include this until the PR with the `Students.vue` is merged. So you should chase people to review and get that merged! 😃

2020-11-07 08:08 UTC, dzldebby commented
> Suggest you separate the changes regarding the Students table and the routes.

Okay, will mark as WIP first until after the Students table is merged.

2020-11-10 10:21 UTC, thchia commented
@dzldebby you can rebase and resolve the conflicts on this now.

2020-11-14 05:36 UTC, thchia approved these changes
LGTM

2020-11-21 02:47 UTC, lauratsui approved these changes
Looks good!

2020-11-22 02:32 UTC, merged