[irrc-71] validations to status updates in backend
TechLadies/irrc-madwish pull request #48
Opened 2020-12-05 05:37 UTC by lauratsui

added validations for status updates - previous status cannot be the same as next status, and prev status should be the same as current status in database

2020-12-07 03:00 UTC, therealyingtong approved these changes

2020-12-07 03:16 UTC, therealyingtong requested changes

2020-12-07 03:16 UTC, therealyingtong commented on backend/src/routes/statusUpdates.js
> +  if (prevStatus.StatusID == nextStatus.StatusID) {
```suggestion
  if (req.body.PreviousStatusID == req.body.NextStatusID) {
```

2020-12-07 03:16 UTC, therealyingtong commented on backend/src/routes/statusUpdates.js
> +  if (student.StatusID !== prevStatus.StatusID) {
```suggestion
  if (student.StatusID !== req.body.PrevStatusID) {
```

2020-12-07 03:51 UTC, therealyingtong requested changes

2020-12-07 03:51 UTC, therealyingtong commented on backend/src/routes/statusUpdates.js
> +        nextStatus: nextStatus.StatusID
```suggestion
        previousStatus: req.body.PreviousStatusID,
        nextStatus: req.body.NextStatusID
```

2020-12-07 03:51 UTC, therealyingtong commented on backend/src/routes/statusUpdates.js
> +        submittedStatus: prevStatus.StatusID,
```suggestion
        submittedStatus: req.body.PreviousStatusID,
```

2020-12-12 04:39 UTC, thchia commented
@therealyingtong suggested changes made!

2020-12-12 05:07 UTC, therealyingtong approved these changes

2020-12-26 15:31 UTC, xuanjane approved these changes
LGTM :)

2020-12-29 05:34 UTC, merged