[IRRC-19] Create matching table
TechLadies/irrc-madwish pull request #73
Opened 2021-01-02 07:24 UTC by dzldebby

2021-01-16 03:10 UTC, szktm requested changes
LGTM, just needs a minor change before merging - the "matched selected" button should be "confirm selected" (see Figma).

2021-01-16 03:13 UTC, szktm commented on frontend/src/pages/Matching.vue
> +                  <span>Matched selected </span> ({{ checkedRows.length }})
should be "confirm selected" as the button leads to a pop-up saying that matches will be confirmed + an email will be sent to teachers

2021-01-17 04:31 UTC, szktm approved these changes

2021-01-22 05:50 UTC, therealyingtong requested changes

2021-01-22 05:50 UTC, therealyingtong commented on backend/src/routes/statusUpdates.js
> +
```suggestion
```
`result` is declared on line 66.

2021-01-22 05:50 UTC, therealyingtong commented on frontend/src/store.js
> +} from "./store/matching.js"
```suggestion
} from "./store/matching.js";
import {
```

2021-01-22 05:50 UTC, therealyingtong commented on frontend/src/store.js
> +    ...matchingState
```suggestion
    ...matchingState,
```

2021-01-22 05:50 UTC, therealyingtong commented on frontend/src/store.js
> +    ...matchingMutations
```suggestion
    ...matchingMutations,
```

2021-01-22 05:50 UTC, therealyingtong commented on frontend/src/store.js
> +
The `updateStudentStatus()` and `updateStudentEnglishProficiency()` actions are already present in `frontend/src/store/students.js` under `studentActions`. (Do verify this for yourself.)

```suggestion
```

2021-01-23 03:26 UTC, therealyingtong approved these changes

2021-01-23 03:26 UTC, merged