Create and save student with null English Proficiency
TechLadies/irrc-madwish pull request #89
Opened 2021-01-23 06:43 UTC by szktm

Fixes #84 by deleting EnglishProficiency from the request body to POST/PATCH whenever EnglishProficiency is "" or null. 

We couldn't post students with no EngProf from the frontend as an empty EngProf would be sent to the backend as EnglishProficiency: "" instead of not being sent at all. Then it'd fail as it violates the constraints for EngProf (as "" is not one of the enum values).

2021-01-26 11:11 UTC, therealyingtong approved these changes

2021-01-26 11:18 UTC, therealyingtong requested changes

2021-01-26 11:18 UTC, therealyingtong commented on backend/src/routes/students.js
> +  if (req.body.EnglishProficiency === "" || null) {
Due to [logical operator precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence), `if (string === "something" || null)` is parsed as `(if string === "something") OR (if null)`, whereas we want `if string === ("something" OR null)`

```suggestion
  if (!req.body.EnglishProficiency || req.body.EnglishProficiency === "") {
```

2021-01-30 06:18 UTC, lauratsui reviewed
LGTM pending yingtong's comment, thanks!

2021-02-05 16:02 UTC, szktm commented
Thank you @therealyingtong for catching the issue with logical operators and laura for reviewing! i've committed the changes such that it checks that the contents of req.body.EnglishProficiency are null

2021-02-06 02:34 UTC, thchia approved these changes

2021-02-07 12:19 UTC, therealyingtong approved these changes

2021-02-20 02:08 UTC, merged