Issue #86: Status card updates after changing status
TechLadies/irrc-madwish pull request #90
Opened 2021-01-23 08:16 UTC by szktm

Fixes #86 by using computed properties — data is now reactive, and cards will change after status is changed (e.g. clicking Drop Out + confirm will change the status card to Dropped Out, clicking "reactivate for Screening" will change the card to Screening)

2021-01-24 13:47 UTC, maryanahermawan requested changes
Tested it's working well.
Suggest to clean up
1) at store students.js: A)updateStudentStatus function is not async, B)move dispatch('getAllStudents') to first then block (second then block is not needed as the first one does not return a promise).
![image](https://user-images.githubusercontent.com/22461722/105632270-30611300-5e8d-11eb-97f3-501c5aefb79a.png)
2) In ModalDroppedOut.vue: this.updateStudentStatus is not returning a promise so there is no need for .then block.
![image](https://user-images.githubusercontent.com/22461722/105632342-88981500-5e8d-11eb-8d8a-d8cd98b37362.png)
3) I tried adding reason, the window is chopped off the edge:
![add new reason window behaving unusually](https://user-images.githubusercontent.com/22461722/105633318-d8c5a600-5e92-11eb-89d5-3391a2e54e52.JPG)

What do you think of this? Let me know if you think otherwise.

2021-01-24 17:02 UTC, aelbore commented
i dont see any store.js included to this PR. 
I think its not mandatory to put async in the function if you dont have await inside the function. 
Maybe lets refactor the promise.then to async/wait to look cleaner and easy to understand.

2021-01-26 11:26 UTC, therealyingtong approved these changes

2021-01-26 11:30 UTC, therealyingtong requested changes

2021-01-26 11:30 UTC, therealyingtong commented on frontend/src/components/modals/ModalDroppedOut.vue
> +    width: 640px
```suggestion
.modal-card-body{
    width: auto
}
.modal-card-foot{
    width: auto
```

2021-01-26 11:32 UTC, therealyingtong commented on frontend/src/components/statusCards/StatusCardDroppedOut.vue
> +    ...mapActions([ 'updateStudentStatus']),
(just nitpicking here)

```suggestion
    ...mapActions(['updateStudentStatus']),
```

2021-01-30 06:11 UTC, lauratsui approved these changes
LGTM, pending the requested changes that have already been raised

2021-02-06 06:57 UTC, szktm commented
hi @maryanahermawan and @therealyingtong, I've just made the requested changes! please let me know if it works better now / if the modal still gets cut off. thank you for your comments!

2021-02-06 09:30 UTC, dzldebby approved these changes
Tested and modal doesn't cut off. Status card is reactive, works well!

2021-02-07 12:16 UTC, therealyingtong approved these changes

2021-02-09 14:28 UTC, merged